completed Aleksandr's task
racerx8000/JS_homework pull request #4
Opened 2021-02-21 19:36 UTC by racerx8000

2021-02-21 19:59 UTC, GavukaAlexandr commented on aleksandrTask/task.js
> +  return promise =  new Promise((resolve, reject) => {
Якщо ти повертаєш значення, то в JS не обов`язково його перед цим присвоювати змінній, можна просто повертати результат :) так коротше і чистіше розуміння
return new Promise(resolve => {
аргементи коллбеків які не використовуєш іноді можна також не використовувати
все інше, в цілому добре

2021-02-25 17:16 UTC, rtm7777 requested changes

2021-02-25 17:16 UTC, rtm7777 commented on aleksandrTask/task.js
> +timeout(2000).then((result) => console.log(result));
add new line at the end of the file

2021-02-25 17:16 UTC, rtm7777 commented on aleksandrTask/callbackFunc.js
> +  console.log('resloved');
remove this :) you need to add `console.log` at the end, where you actually call this function

2021-02-25 17:16 UTC, rtm7777 commented on aleksandrTask/callbackFunc.js
> +  console.log('resloved');
After you do it I'll add another feedback, it's time to learn how to shorthand this a little

2021-03-08 09:07 UTC, rtm7777 approved these changes

2021-03-21 19:35 UTC, merged